[build]
command = ""          # אין תהליך build – סטטי
publish = "public"    # כאן נמצא index.html

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
